---
title: "COBI's Q&A to data"
date: "May 4, 2016"
output: 
  ioslides_presentation: 
    transition: faster
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Structure

- Design of data collection (matching goals and data)

- What they are collecting (and how)

- Uses of that data

## Design of data collection

- Establish a baseline (biophysical, socioeconomic, governance)

>- Objectives/goals are set when the Marine Reserve is designed

>- What to monitor depends on objectives of the reserve (partial, total, temporal, permanent?)

>- Design **databases** and select **analysis** (failed [Eureka](http://eurekamarine.org/about-en/))

>- Select periodicity of surveys

## What COBI is gathering

- Baseline

>- Underwater ecological surveys: abundance, sizes, richness of key species(harvested, sentinel, or of interest)

>- Equal frequency of monitoring between reserve and control: once a year (roughly same time)

>- **No systematic** monitoring of socioeconomics and governance --> in process of implementing it (Mario Rojo)

>- **No systematic** monitoring of landings (just for certified fisheries), but NOM-049 requires it --> Also in the process (Antonio G?mez)

## What COBI has been asking

Information (trends, time series) that can be presented to:

- Fishers and other users (assembly of fishers or comittees of MPAs)

>- Agencies and individuals responsible for conservation and fisheries management (SAGARPA ~ SEMARNAT)

>- Results that lead to:

>- Adaptation of management strategies

>- **No evaluation of effectiveness, yet**

# Questions?

# Extra slides

## What COBI wants (this project)

A way to evaluate No Take Zones (different) that allows them to adapt management:

>- How am I doing? (and what I need to know to ask that question)

>- What should I do to be better?

## Community involvement

- COBI evaluates which set of indicators are subject to be compiled by community members

>- All communities have "survey divers" that are trained (accordingly) to monitor their *reserves and control* sites (selection criteria)

>- Some communities have members that have been trained in *Oceanographic monitoring*

>- Other data is gathered by NGO's, Government Agencies, Research Institutes or any *combination of the above*

## About Eureka

You can add information (abundance and size) for invertebrate and fish species monitored with transects quadrants or cylinders of any size.

You may also compare the information on abundance and size on any species inside and outside of the no-take zones over time (yearly), and obtain a graphic report of this comparison, and per site.


